version: '3'
services:
  galaxy:
    image: quay.io/erasmusmc_bioinformatics/streeklab-haarlem-galaxy
    #restart: always
    ports:
      - 8080:80
    volumes:
      - /root/galaxy_docker/galaxy_storage_HLA/:/export/
    environment:
      - "GALAXY_CONFIG_INSTALL_DATABASE_CONNECTION=true"

  mycrobiota:
    image: quay.io/erasmusmc_bioinformatics/streeklab-haarlem-galaxy-mycrobiota
    #restart: always
    ports:
      - 8081:80
    volumes:
      - /root/galaxy_docker/galaxy_storage_MYcrobiota/:/export/
    environment:
      - "GALAXY_CONFIG_INSTALL_DATABASE_CONNECTION=true"

