version: '3'
services:
  galaxy:
    image: quay.io/erasmusmc_bioinformatics/streeklab-haarlem-galaxy
    #restart: always
    ports:
      - 8080:80
    volumes:
      - /home/user/galaxy_storage/:/export/
  mycrobiota:
    image: quay.io/erasmusmc_bioinformatics/streeklab-haarlem-galaxy-mycrobiota
    #restart: always
    ports:
      - 8081:80
    volumes:
      - /home/user/galaxy_storage_mycrobiota/:/export/

