# Galaxy - Streeklab Haarlem
#
# Contains:
#   - MYcrobiotat pipeline
#   - HLADQ pipeline
#   - JAK2 pipeline
#
# This docker image is available from quay.io:
#    docker run -p "8080:80" quay.io/shiltemann/galaxy-streeklab-haarlem
#
# To build this docker image locally:
#    docker build -t <your tag name> .
#

FROM bgruening/galaxy-stable

MAINTAINER Saskia Hiltemann (zazkia@gmail.com)

ENV GALAXY_CONFIG_BRAND "Streeklab"


